config.localisation.bathymetric_names = [
  //Hesteria
	/*
  	"Roder Bay",
  	"Valour Strait",
  	"Fortitude Bay",
  	"Sedenal Sea",
  	"Sedenal Islands",
  	"Coast of Amsai",
  	"Heunghoi Strait",
  	"Gwokga Delta",
  	"Gulf of Haerjo",
  	"North Tereles Passage",
  	"Tereles Ocean",
  	"Ashima Straits",
  	"Lampshaden Plateau",
  	"Strait of Accalma",
  	"Mid-Seperic Ridge",
  	"Cape Circle",
  	"Okoye Delta",
  	"Sirenis Sea",
  	"Sedes Strait",
  	"Australic Strait",
  	"Lines Strait",
  	"Tetralic Gulf",
  	"Novaenian Sea",
  	"Noveinter Passage",
  	"Rampan Sea",
  	"Bercault Isthmus",
  	"Gulf of Nocte",
  	"Gren Isthmus",
  	"Cape Discoir",
  	"Seperic Ocean",
  	"Cliffs of Runsend",
  	"Sepention Island",
  	"Aelfland",
  	"Hesteric Pass",
  	"Gulf of Hesteria",
  	"Litlandic Shelf",
  	"Collenham Delta",
  	"Trommen Bay",
  	"Intersectionalic Sea",
  	"Karelekt",
  	"Presteric Ocean",
  	"Borealic Ocean",
  	"Thoric Pillars",
  	"Cacarra Coast",
  	"Artisa Passage",
  	"Gulf of Titania",
  	"Torrentes Sea",
  	"Australis Shelf",
  	"Terrace Bridge",
  	"Great Australic Sea",
  	"Southern Ocean"
	*/
	//Earth
	"Baffin Bay",
	"Davis Strait",
	"the Labrador Sea",
	"Cumberland Sound",
	"the Gulf of St. Lawrence",
	"Maine",
	"Fundy",
	"Nantucket Sound",
	"Narragansett Bay",
	"Long Island Sound",
	"Chesapeake Bay",
	"Cape Hatteras",
	"the Gulf of Mexico",
	"the Carribean Sea",
	"Todos os Santos",
	"Guanabara Bay",
	"Lagoa dos Patos",
	"the River Platte",
	"the Argentine Sea",
	"the Norweigan Sea",
	"Kattegat",
	"Skaggerak",
	"Dogger Bank",
	"the Baltic Sea",
	"the Gulf of Bothnia",
	"Kvarken",
	"the Bothnian Sea",
	"Aland",
	"the Gulf of Finland",
	"Vyborg",
	"Neva",
	"Koporye",
	"Narva Bay",
	"the Gulf of Riga",
	"Gdansk Bay",
	"the Kalmar Straits",
	"the Danish Straits",
	"Hanö Bight",
	"the Oresund Strait",
	"the English Channel",
	"the Strait of Dover",
	"the Irish Sea",
	"the Celtic Sea",
	"St. George's Strait",
	"the Iroise Sea",
	"the Bay of Biscay",
	"the Cantabrian Sea",
	"the Gulf of Cádiz",
	"the Mediterranean",
	"the Alboran Sea",
	"the Balearic Sea",
	"the Gulf of Lions",
	"the Ligurian Sea",
	"the Tyrrhenian Sea",
	"Elba",
	"the Adriatic",
	"the Ionian Sea",
	"the Aegean Sea",
	"the Sea of Marmara",
	"Reggio di Calabria",
	"the Levantine Sea",
	"the Libyan Sea",
	"the Strait of Sicily",
	"Gabes Gulf",
	"Sirte Gulf",
	"Sardinia",
	"Corsica",
	"the Black Sea",
	"the Sea of Azov",
	"the Kerch Strait",
	"Sebastopol",
	"the Gulf of Guinea",
	"Walvis Bay",
	"Luanda Bay",
	"False Bay",
	"the Cape of Good Hope",
	"the Irminger Sea",
	"the Denmark Strait",
	"the Hebrides",
	"the Magallanes",
	"the Tierra del Fuego",
	"the Falklands",
	"the Andaman Sea",
	"the Arabian Sea",
	"the Gulf of Kutch",
	"the Gulf of Khambhat",
	"the Bay of Bengal",
	"the Gulf of Aden",
	"the Gulf of Oman",
	"the Laccadive Sea",
	"Mozambique Channel",
	"the Persian Gulf",
	"the Red Sea",
	"the Sea of Zanj",
	"the Timor Sea",
	"Palk Strait",
	"Palk Bay",
	"Gulf of Mannar",
	"the Bering Sea",
	"Bristol Bay",
	"Norton Sound",
	"the Chilean Sea",
	"the Aleutians",
	"the Gulf of Alaska",
	"Glacier Bay",
	"Prince William Sound",
	"the Gulf of California",
	"the Gulf of Nicoya",
	"Panama Bay",
	"the California Coast",
	"the Arafura Sea",
	"the Bali Sea",
	"the Banda Sea",
	"the Bay of Kampong Som",
	"the Bay of Plenty",
	"the Bismarck Sea",
	"the Bohai Sea",
	"the Camotes Sea",
	"the Mindanao Sea",
	"the Celebes Sea",
	"the Ceram Sea",
	"the Coral Sea",
	"the Dragon's Sea",
	"East China Sea",
	"Tsushima Strait",
	"Kagoshima Bay",
	"Flores Sea",
	"the Gulf of Carpentaria",
	"the Gulf of Thailand",
	"the Bay of Bangkok",
	"Halmahera",
	"Hawke's Bay",
	"the Java Sea",
	"the Koro Sea",
	"the Molucca Sea",
	"Philippine Sea",
	"Leyte Gulf",
	"Sagami Bay",
	"the Savu Sea",
	"the Sea of Japan",
	"the Sea of Okhotsk",
	"the Sibuyan Sea",
	"the Solomon Sea",
	"the South China Sea",
	"the West Philippine Sea",
	"the South Seas",
	"Pearl Harbour",
	"the Gulf of Tonkin",
	"the Sulu Sea",
	"the Tasman Sea",
	"Tokyo Bay",
	"the Visayan Sea",
	"Waihau Bay",
	"the Yellow Sea",
	"the Korean Sea",
	"the Sargasso Sea"
];
config.localisation.battle_prefixes = [
  "Hill",
  "Mountain",
  "Peak",
  "Road",
  "Route",
  "Site",
  "Valley"
];
