module.exports = {
  getDefaultProvinceStyling: function () {
    //Return statement, generated by Inkscape
    return "stroke:#000000;stroke-width:0.26458332px;stroke-linecap:butt;stroke-linejoin:miter;stroke-opacity:1;opacity:1";
  },

  setProvinceColour: function (arg0_file, arg1_province_id, arg2_colour) {
    //Convert from parameters
    var local_map = global[`${arg0_file}_parsed`];
    var province_id = arg1_province_id;
    var colour = arg2_colour; //Provided as [r, g, b] array

    local_map.querySelector(`#${province_id}`).setAttribute("style", `fill:${RGBToHex(colour[0], colour[1], colour[2])}${getDefaultProvinceStyling()}`);
  }
};
